
.define VERSION 1
.define REGION NTSC
.define ROM_NAME "BAT CAVE"


.define CONSOLE_HEIGHT 2
.define CONSOLE_MARGIN_TOP 0
.define CONSOLE_MARGIN_BOTTOM 2
.define CONSOLE_MARGIN_LEFT 0
.define CONSOLE_MARGIN_RIGHT 31

